# Generated by Django 4.0.3 on 2022-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_minutes',
        ),
    ]
