# Generated by Django 4.0.3 on 2022-05-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recipe_time_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
